### PR TITLE
Remove timex

### PR DESCRIPTION
**Pull request by radar**
Hey again :)

I noticed this morning that Timex 2.0 has a few dependencies, which increases the compile time for projects that use `aws_auth`. Here's the dependencies as shown by `mix deps.tree`:

```
│       └── timex ~> 2.0 (Hex package)
│           ├── combine ~> 0.7 (Hex package)
│           ├── gettext ~> 0.10 (Hex package)
│           └── tzdata ~> 0.1.8 or ~> 0.5 (Hex package)
│               └── hackney ~> 1.0 (Hex package)
│                   ├── certifi 0.4.0 (Hex package)
│                   ├── idna 1.2.0 (Hex package)
│                   ├── metrics 1.0.1 (Hex package)
│                   ├── mimerl 1.0.2 (Hex package)
│                   └── ssl_verify_fun 1.1.0 (Hex package)
```

The same goes for timex 3.0:

```
├── timex ~> 3.0 (Hex package)
│   ├── combine ~> 0.7 (Hex package)
│   ├── gettext ~> 0.10 (Hex package)
│   └── tzdata ~> 0.1.8 or ~> 0.5 (Hex package)
│       └── hackney ~> 1.0 (Hex package)
│           ├── certifi 0.4.0 (Hex package)
│           ├── idna 1.2.0 (Hex package)
│           ├── metrics 1.0.1 (Hex package)
│           ├── mimerl 1.0.2 (Hex package)
│           └── ssl_verify_fun 1.1.0 (Hex package)
```

This library only uses timex for time/date formatting, which can be accomplished using the built-in  date/time functions in Elixir 1.3+. With the timex dependency removed, then the compile time for my project is much faster.

I think this will require a major version bump for aws_auth.

### CODE REVIEW

**Comment by bryanjos** [comment]
Nice! I will bump it to 0.6.0 since it's still not 1.0, but I should probably just make this 1.0 now anyway since people are using it.

Also, if you're interested in becoming a collaborator on the project let me know. I don't use this much anymore, I know others do, and I always feel bad that I don't give it as much love as it deserves.

**Comment by radar** [comment]
Sure, I'll become a collab on it.

**Comment by bryanjos** [comment]
awesome! I've added you

**Comment by radar** [comment]
@bryanjos I am not sure if you added me as a collab on GitHub? I can't merge #27, which makes me think that I am not a collab?

**Comment by bryanjos** [comment]
@radar check your email, looks like you haven't accepted. I can merge it in the meantime

**Comment by radar** [comment]
Found it, thanks :)

**Comment by radar** [comment]
@bryanjos Could you please add me on `hex.pm` too?

```
mix hex.owner add me@ryanbigg.com aws_auth
```

If the email doesn't work there, then perhaps `radar` will.

**Comment by bryanjos** [comment]
Added!

**Pull request merged**
