### PR TITLE
x-amz-date should present at headers; return headers with x-amz-date …

### PR DESCRIPTION
**Pull request by belousovAV**
x-amz-date should present at headers
Return headers with x-amz-date and authorization to use at request as it is

### CODE REVIEW

**Comment by radar** [comment]
As with #28, steps to reproduce an issue here too please.

**Comment by belousovAV** [comment]
We can use it now without this fix. But workflow for #query_params is two step:

1. encode data to url
2. query it.

Workflow for headers:

1. Put to header 
`headers = Map.put(headers,"x-amz-date", AWSAuth.Utils.format_time(this_time))`,
due to 
`{:error, 403, "{\"message\":\"Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header....`.
 Also, we must to calculate time and can't skip it to [default](https://github.com/bryanjos/aws_auth/blob/master/lib/aws_auth.ex#L85)
2. Sign this headers, and get "authorization" header. `auth_header = AWSAuth.sign_authorization_header(..., this_time, headers)`
3. Put this new header to our headers. 
`Map.put(headers, "authorization", auth_header)`
4. Request.

With this fix we can sign headers and pipe result to request and we have not to prepare time.

Sorry for my english.

**Comment by radar** [comment]
Thank you for the PR. I just noticed today that this seems to break the tests. 

```
  1) test sign_authorization_header PUT (AWSAuthTest)
     test/aws_auth_test.exs:32
     ** (MatchError) no match of right hand side value: [{"Date", "Fri, 24 May 2013 00:00:00 GMT"}, {"authorization", "AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20130524/us-east-1/s3/aws4_request,SignedHeaders=date;host;x-amz-content-sha256;x-amz-date;x-amz-storage-class,Signature=ea8420f895f2d833ec414e8c195a8e673663d0077f11f303760aac8639ff31b5"}, {"host", "examplebucket.s3.amazonaws.com"}, {"x-amz-content-sha256", "44ce7dd67c959e0d3524ffac1771dfbba87d2b6b4b4e99e42034a8b803f8b072"}, {"x-amz-date", "20130524T012345Z"}, {"x-amz-storage-class", "REDUCED_REDUNDANCY"}]
     stacktrace:
       test/aws_auth_test.exs:47: (test)

...

Finished in 0.1 seconds
4 tests, 1 failure
```

Could you please investigate this?

**Review by radar — APPROVED** [review]

**Comment by radar** [comment]
Thank you!

**Comment by radar** [comment]
I have released 0.6.3 with this change in it.

**Pull request merged**
