### PR TITLE
Add license to project

### PR DESCRIPTION
**Pull request by kennyballou**
Add the license file to the project, make it more explicit that the project is licensed apache 2.0

### CODE REVIEW

**Comment by kennyballou** [comment]
After some more thought, this kind of change requires the sign-off on all past contributors. Sorry for the mass summon...

If you approve of this change, please add a quick sign off.

- [ ] @radar
- [ ] @bryanjos
- [ ] @ernie
- [ ] @asonge
- [ ] @bgentry
- [ ] @belousovAV 
- [ ] @cmedley 
- [ ] @kenta-aktsk 
- [ ] @zzanger 
- [ ] nstice (at ) gmail (dot) com

**Comment by radar** [comment]
I'd be happy with an MIT but really it's @bryanjos project so I'll leave it with him.

**Comment by bgentry** [comment]
Same answer here. I'd prefer MIT, but ok with Apache 2.0 if that's what @bryanjos chooses.

**Comment by bryanjos** [comment]
I'm also fine with MIT

**Comment by kennyballou** [comment]
Reason I deleted the comment was because I noticed this line: https://github.com/bryanjos/aws_auth/blob/3621653a122719ff6b454320ec06289e000081bc/mix.exs#L39

Because of this, it would be safe to merge this with no issue. If, however, it's preferred to go the path of _changing_ the license to MIT, we would need to get everyone's approval. Less friction to maintain Apache 2.0.

**Comment by radar** [comment]
Well that seems pretty clear cut to me!

**Comment by radar** [comment]
Thank you @kennyballou :heart:

**Pull request merged**
