### PR TITLE
Fix issues with signing Elastic Beanstalk requests

### PR DESCRIPTION
**Pull request by ernie**
Hi Bryan,

Thanks so much for this library. I was running into issues signing requests for the Elastic Beanstalk service, and needed these changes in order to mach Amazon's expectations. I'm spoiled by libraries with other languages, so I suspect this change might be a breaking one for some of Amazon's other services, based on what I've read.

I ran tests on my local machine on the master branch and had some failures already -- Unsure if maybe timex has made some breaking changes or something else is going on, so I'm sorry this doesn't include tests but I am hopeful this at least helps someone else troubleshoot. :(

### CODE REVIEW

**Comment by bryanjos** [comment]
Sorry I've been meaning to reply to this. I can take a closer look this weekend and see if anything breaks. I'd be interested in seeing what @benwilson512 has to say as well. His library, [ex_aws](https://github.com/CargoSense/ex_aws) is building a set of AWS APIs and uses this one. So it could have an effect on ex_aws.

I've been thinking about discussing with him if it makes sense to merge this library into that one.

**Comment by benwilson512** [comment]
Well you should feel free to make any updates you think are appropriate, I can work around them. That said, I have considered moving auth signing "in house" so to speak just because various services tend to do it differently and moving it in house with let me build the signing process in such a way that accommodated my particular use cases more.

Put another way, do what you like, I'll either work around it or more auth in house.

**Comment by ernie** [comment]
No apologies needed on my end, @bryanjos. And yeah, @benwilson512, I've been so spoiled by AWS SDKs that I had no idea until tackling this just how differently the request signing works depending on the service being accessed. :(

**Comment by bryanjos** [comment]
@ernie thanks! I still haven't taken a full look yet, but I'm going to give this some more love soon.

**Pull request merged**
